version: '3'
services:
  frontend:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      # olhar https://ghost.org/docs/config/
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=password
      - database__connection__database=ghost
    depends_on:
      - db
  db:
    platform: Linux/x86_64 # Caso utilize MacOS, descomente essa linha
    image: mysql:5.7.40
    environment:
      - MYSQL_ROOT_PASSWORD=password